Use the server session to get bond names instead of parsing the notebook code
JuliaPluto/PlutoSliderServer.jl pull request #97
Opened 2022-11-19 13:08 UTC by disberd

The current way PlutoSliderServer finds bonds is by going through the parsed cell code and looking for the presence of the `@bind` variable:
https://github.com/JuliaPluto/PlutoSliderServer.jl/blob/01f611277c962e0087767f9547b8f4b6591f0214/src/MoreAnalysis.jl#L14-L28

This unfortunately do not work for custom macros that internally create bonds.

The SliderServer already instantiate a Pluto Server session so we can directly access the bound variables that are recorded inside the PlutoRunner module. This makes it easier to track all possible bound variables without resorting to complex rules for parsing the code within the cell inputs

2022-12-08 16:10 UTC, disberd commented
@fonsp this is now ready for review

2022-12-12 13:27 UTC, fonsp requested changes
Inlcuding HypertextLiteral and running the notebook makes the tests run in 7 minutes instead of 5. Could you write a macro that does not use HypertextLiteral? Maybe a macro that just adds "123" to the bound variable name?

If that's not a good idea for some reason then the extra 2 minutes is fine 👍

2022-12-13 09:45 UTC, disberd commented
@fonsp I did just use the example you gave me on zulip :D, didn't think about timing impact but I removed HypertextLiteral and just used Markdown now which should not impact the time

2022-12-13 11:42 UTC, fonsp approved these changes

2022-12-13 11:48 UTC, merged